unique_ids:
  assets:
    baseball.jpeg: '1678065697727814019744342.9333'
    hank3.jpg: ZS6SYKGZ765JVJCAOVUXN2MOXO5Z5TBD
    judge.jpeg: '167806576422863134595383.83848'
    standard-page.html: WZM5IDCNMF6F4SE4DFUOH7C4276UK4WP
    theme.css: FPCWVNJ4I7O4MFROE5JEQAD7LTRCY75S
  forms:
    Analytics: U65MHD3LVZVFEF5CAP5KR6UBISOYGOYV
    Form1: OV3W5FPROCN6UYADUVLDKIJISBMDYDUR
    Form1.RowTemplate7: FNLMZ6XOP4XEXRTYJJBKAKLCQPVLWUFJ
    HomeContent: NOALR6AA4CV4HFJ3HUL6JOEVBMA6FNWX
    HomePage: EMHSDXPBK7OOSSX4BPV2IJUFYUEZYBR7
    Homers: BCNZRCBIKGUR2X7LNYCAQF7H2JANM535
    Homers.RowTemplate3: JOKOWULASJSNSOF7PBLUAWOXPR5EQ7SL
    ItemTemplate1: 4CW6I2ZOGJ2VLK6N7RZGZJ4P6Y6UFKGN
    ItemTemplate2: MKWY6ETGV4EZTHBFEIXHUXUJWXYN4UKB
    ItemTemplate3: RA22RN2SQNTIEAND3QIDOGYI4EVC34HO
    ItemTemplate4: TCM4AXQHEQ4JO4JRLTVHB3SWTXFHZHZJ
    ItemTemplate5: XHOTNU7CIFMUJY4KA34SCDJBMNJCLSFL
    ItemTemplate6: TIAVOAZE7RDM5MITRGJTPYCM3RL7HA3B
    Players: NIB3GSUQSQJ3Y65WGPHBPT4244XUCA6C
    Players.RowTemplate2: BPLOTEV2MF6CQ5JUVVFC6FN5KGPTJJWS
    PlayersToTeams: CFJRY2DMXGB5P73CB6K6EC2NT6BPISC4
    Print: DRKM5G6G34AXINBNOADULZUJF4LW5BK4
    Prizes: '1711728131433994159020270.5535'
    RowTemplate10: UQJDLUC6PGX5MCQULYF4E2QE5B4LWMYE
    RowTemplate5: L6X56EJE356FF4MSRRW52TXZ4SDUEWS4
    RowTemplate6: IBPB73Q7EG5UONMEZSJWDDUDC6YGU66B
    RowTemplate8: MXO5YNLLWGIHK5W5PELWIQRSANYHF2PV
    RowTemplate9: JRQH53WTIURHIZTEQJFQQUDRLEN6MB3W
    ShowTeams: C5ITQ3UI7IWYX3WGBS2URGSBFJ6BLM44
    SplashScreen: 3FVUJEAKXTS3OSQPD34O7RWYCECWXUXL
    Standings: 4VMSNUVQBWLCBP77N2MTGKLDEFC3F2WN
    Standings.RowTemplate1: MARA5KFOVIWP2BJXT6PPSZ67Z6G3FBAH
    Standings.RowTemplate1.RowTemplate4: BGCQSKGVWDTPETFR453ESGR4Z2RR5W3F
    TeamColumn: 7MYT7DDS6HSQOOTDDEFCYBF4THOEVA3N
    TeamPicker: 2ATCSLP6HQLGMVV5JFIXD7CLJG75WQK2
    WhosHot: FMKVGP5FVUIXSOTJ27USF4FSTN4SR5VU
    hankandtitle: WDSDQWNYOTLKFANFEJWNU37REKVPINQH
    signup: '1708722970721522196618954.33655'
    teamrow: 7V5VHQBSL5YJ6RRKLD5FJPCOVMIN62TT
  modules:
    Module1: SR4S57XGGTULZ5MWNTE5MGJ3TDUETIYS
    data_access: DHQTB3EIOT5IGPC5YD6NAZODKTJPK2NN
    navigation: VRLXZZX5C4NDRP3B3BHFVIUM7LR7QJZB
  scripts: {}
  server_modules:
    ServerModule1: '1762457474282844434631309.6489'
    admin: 2F4DQGN7PA6HZX7FX2CCBVULHDSYJVAN
    update: JHR2KO25VGKBAF2TM2LUK2FLMHYJNYSY
    wfs: A374KHASDKVBW5QI3DAYYIK6VQQV2QKI
